"use client";
import {AppShell} from "@/components/app-shell";
import type {AnnouncementRecord,EventRecord} from "@/lib/domain";
import {formatEventDate,formatShortDate} from "@/lib/domain";
import {getSupabaseBrowserClient} from "@/lib/supabase/client";
import {CalendarDays,ChevronRight,CircleDollarSign,Database,Gauge,MapPin,ShieldCheck,UsersRound} from "lucide-react";
import Image from "next/image";
import {useEffect,useState} from "react";

type DashboardStats={total_members:number;total_km:number;cash_balance:number;last_updated:string|null};

export default function HomePage(){
 const[events,setEvents]=useState<EventRecord[]>([]),[announcements,setAnnouncements]=useState<AnnouncementRecord[]>([]),[stats,setStats]=useState<DashboardStats|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[signedIn,setSignedIn]=useState(false),[statsError,setStatsError]=useState("");
 useEffect(()=>{let active=true;const load=async()=>{try{const supabase=getSupabaseBrowserClient();const[{data:{user}},eventResult,bulletinResult]=await Promise.all([supabase.auth.getUser(),supabase.from("events").select("id,title,slug,type,description,location_name,location_url,start_at,end_at,meetup_at,status").eq("status","published").gte("start_at",new Date().toISOString()).order("start_at").limit(3),supabase.from("announcements").select("id,title,body,published_at").eq("is_published",true).order("published_at",{ascending:false}).limit(1)]);if(eventResult.error)throw eventResult.error;let nextStats:DashboardStats|null=null;let nextStatsError="";if(user){const statsResult=await supabase.rpc("get_member_dashboard_stats");if(statsResult.error)nextStatsError="Statistik belum dapat dimuat. Coba refresh halaman.";else nextStats=(statsResult.data?.[0]??null)as DashboardStats|null}if(active){setSignedIn(Boolean(user));setEvents((eventResult.data??[]) as EventRecord[]);setAnnouncements((bulletinResult.data??[]) as AnnouncementRecord[]);setStats(nextStats);setStatsError(nextStatsError)}}catch(cause){if(active)setError(cause instanceof Error?cause.message:"Data belum dapat dimuat.")}finally{if(active)setLoading(false)}};void load();const timer=window.setInterval(load,15000);return()=>{active=false;window.clearInterval(timer)}},[]);
 const next=events[0];
 return <AppShell active="Home" title="Member Hub"><div className="dashboard-grid"><div className="left-column">
  <section className="hero"><img className="hero-mark" src="/revolt-riders-logo.jpg" alt="" aria-hidden="true"/><div><em>{next?"AGENDA BERIKUTNYA":"REVOLT RIDERS SITUBONDO"}</em><h2>{next?.title??<>SATU ASPAL.<br/>SATU PERSAUDARAAN.</>}</h2>{next?<><p><MapPin/>{next.location_name??"Lokasi segera diumumkan"}</p><p><CalendarDays/>{formatEventDate(next.start_at)}</p></>:<p><ShieldCheck/>Platform resmi internal Revolt Riders</p>}<a className="primary-action" href="/agenda">LIHAT AGENDA <ChevronRight/></a></div><div className="dial"><small>REVOLT</small><b>{next?formatShortDate(next.start_at).day:"RR"}</b><span>{next?formatShortDate(next.start_at).month:"XXII"}</span></div></section>
  <section className="stats"><article><UsersRound/><span>MEMBER TERDAFTAR<b>{stats?.total_members??(signedIn?"—":"Privat")}</b><small>{stats?"Data produksi":signedIn?statsError||"Memuat statistik…":<a href="/login">Masuk untuk melihat</a>}</small></span></article><article><Gauge/><span>TOTAL KM CLUB<b>{stats?new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(Number(stats.total_km)):signedIn?"—":"Privat"}</b><small>{stats?"Ride tervalidasi":signedIn?statsError||"Memuat statistik…":<a href="/login">Masuk untuk melihat</a>}</small></span></article><article><CircleDollarSign/><span>SALDO KAS<b>{stats?new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",notation:"compact",maximumFractionDigits:1}).format(Number(stats.cash_balance)):signedIn?"—":"Privat"}</b><small>{stats?"Kas Revolt":signedIn?statsError||"Memuat statistik…":<a href="/login">Masuk untuk melihat</a>}</small></span></article></section>
  <section className="card agenda-card"><div className="section-title"><span><em>AGENDA</em><h3>Agenda terdekat</h3></span><a href="/agenda">Lihat semua <ChevronRight/></a></div>{loading&&<p className="system-message">Memuat agenda terbaru…</p>}{error&&<p className="error-message">{error}</p>}{!loading&&!error&&events.length===0&&<div className="inline-empty"><Database/><span><b>Belum ada agenda yang dipublikasikan.</b><small>Agenda baru akan tampil otomatis dari database.</small></span></div>}{events.map(event=>{const d=formatShortDate(event.start_at);return <a className="event" href={`/agenda#${event.slug}`} key={event.id}><time><b>{d.day}</b><small>{d.month}</small></time><div><em>{event.type.toUpperCase()}</em><h4>{event.title}</h4><p>{formatEventDate(event.start_at)}</p></div><ChevronRight/></a>})}</section>
 </div><div className="right-column">
  <section className="profile card"><img src="/revolt-riders-logo.jpg" alt="Revolt Riders"/><em>AKSES MEMBER</em><h3>Profil personal</h3><p>{signedIn?"Lihat member ID, motor, kilometer, dan riwayat agenda kamu.":"Masuk untuk melihat member ID, motor, kilometer, dan riwayat agenda."}</p><a className="dark-action" href={signedIn?"/profil":"/login"}>{signedIn?"BUKA PROFIL":"MASUK KE AKUN"}</a></section>
  <section className="card production-status"><div className="section-title"><span><em>SYSTEM STATUS</em><h3>Production Core</h3></span><ShieldCheck/></div><ul><li><b>Supabase Database</b><span>Aktif</span></li><li><b>RLS & Role Security</b><span>Aktif</span></li><li><b>RSVP Realtime</b><span>Aktif</span></li><li><b>Google Sheets</b><span className="waiting">Menunggu akses</span></li></ul></section>
  {announcements[0]?<a className="bullet" href="/bulletin"><div><em>BULLETIN</em><h3>{announcements[0].title}</h3><p>{announcements[0].body}</p></div><ChevronRight/></a>:<a className="bullet" href="/bulletin"><div><em>BULLETIN</em><h3>Belum ada pengumuman</h3><p>Informasi resmi akan tampil di sini.</p></div><ChevronRight/></a>}
  <section className="support card"><div className="section-title"><span><em>OFFICIAL SUPPORT</em><h3>Support Revolt Riders</h3></span></div><div className="support-grid"><figure className="bold-riders"><div className="support-logo"><Image src="/bold-riders-situbondo.jpg" alt="Bold Riders Situbondo" fill sizes="(max-width: 720px) 45vw, 180px"/></div><figcaption>Bold Riders Situbondo</figcaption></figure><figure className="frtn"><div className="support-logo"><Image src="/frtn.jpg" alt="FRTN" fill sizes="(max-width: 720px) 45vw, 180px"/></div><figcaption>FRTN</figcaption></figure></div></section>
 </div></div></AppShell>
}
