"use client";
import {Bell,Bike,CalendarDays,CircleDollarSign,ClipboardCheck,Home,Menu,Route,ScanLine,Settings,ShieldCheck,Trophy,UserCog,UserRound,UsersRound,X} from "lucide-react";
import {useMemberAccess,type AppRole} from "@/hooks/use-member-access";
import {useMemo,useState,type ComponentType,type ReactNode} from "react";
type NavItem=readonly[string,string,ComponentType];
const primary:readonly NavItem[]=[["Home","/",Home],["Agenda","/agenda",CalendarDays],["Riding","/riding",Bike],["Member","/member",UsersRound],["Profil","/profil",UserRound]];
const community:readonly NavItem[]=[["Kas Revolt","/kas",CircleDollarSign],["Leaderboard","/leaderboard",Trophy],["Bulletin","/bulletin",Bell]];
const memberTools:readonly NavItem[]=[["Check-in","/check-in",ScanLine]];
const roadCaptainTools:readonly NavItem[]=[["Kehadiran","/admin/attendance",ClipboardCheck],["Validasi Ride","/riding/approval",ShieldCheck]];
const adminTools:readonly NavItem[]=[["Kelola Member","/admin/members",UserCog],["Admin","/admin",Settings]];
const hasRole=(role:AppRole|undefined,roles:AppRole[])=>Boolean(role&&roles.includes(role));
export function AppShell({active,title,children}:{active:string;title:string;children:ReactNode}){const[open,setOpen]=useState(false);const{user,account,loading}=useMemberAccess();const secondary=useMemo(()=>{const items:NavItem[]=[...community];if(account?.status==="active")items.push(...memberTools);if(account?.status==="active"&&hasRole(account.role,["road_captain","admin","superadmin"]))items.push(...roadCaptainTools);if(account?.status==="active"&&hasRole(account.role,["admin","superadmin"]))items.push(...adminTools);return items},[account]);const accountLabel=loading?"Memuat":!user?"Masuk":account?.status==="active"?"Profil":account?.status==="inactive"?"Nonaktif":"Verifikasi";const nav=(items:readonly NavItem[])=>items.map(([label,href,Icon])=><a className={active===label?"active":""} href={href} key={label} onClick={()=>setOpen(false)}><Icon/>{label}</a>);return <main className="app-shell"><aside className={open?"open":""}><a className="brand" href="/" aria-label="Revolt Riders home"><img src="/revolt-riders-logo.jpg" alt="Logo resmi Revolt Riders"/><strong>REVOLT RIDERS<small>MEMBER HUB</small></strong></a><button className="close-menu" onClick={()=>setOpen(false)} aria-label="Tutup menu"><X/></button><nav>{nav(primary)}</nav><p className="navlabel">KOMUNITAS</p><nav>{nav(secondary)}</nav><div className="motto"><Route/><span><b>Ride safe.</b><small>Brotherhood tanpa batas.</small></span></div></aside>{open&&<button className="shade" onClick={()=>setOpen(false)} aria-label="Tutup menu"/>}<section className="content"><header><button className="hamb" onClick={()=>setOpen(true)} aria-label="Buka menu"><Menu/></button><div><small>REVOLT RIDERS · SITUBONDO</small><h1>{title}</h1></div><div className="tools"><span className="live-dot">● LIVE</span><a className={`login-link${account?.status&&account.status!=="active"?" account-warning":""}`} href={user?"/profil":"/login"}>{accountLabel}</a></div></header>{children}</section><nav className="bottom">{primary.map(([label,href,Icon])=><a key={label} className={active===label?"active":""} href={href}><Icon/><small>{label}</small></a>)}</nav></main>}
export function SyncPending({area}:{area:string}){return <section className="empty-state card"><span className="status-dot"/><h2>{area} siap dihubungkan</h2><p>Modul production sudah tersedia. Data akan tampil setelah akses Google Sheets untuk server dikonfigurasi.</p></section>}
