/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
"use client";
import type {PublicInvitation} from "@/lib/domain";
import {formatEventDate} from "@/lib/domain";
import {getSupabaseBrowserClient} from "@/lib/supabase/client";
import {CalendarDays,Check,MapPin,X} from "lucide-react";
import {useParams} from "next/navigation";
import {useEffect,useState} from "react";
export default function InvitationPage(){const params=useParams<{token:string}>(),token=String(params.token??"");const[data,setData]=useState<PublicInvitation|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");const load=async()=>{const{data,error}=await getSupabaseBrowserClient().rpc("get_public_invitation",{p_token:token});if(error)setError(error.message);else setData(((data??[])[0] as PublicInvitation|undefined)??null);setLoading(false)};useEffect(()=>{void load()},[token]);const answer=async(status:"attending"|"declined")=>{setSaving(true);setError("");const{error}=await getSupabaseBrowserClient().rpc("submit_invitation_rsvp",{p_token:token,p_status:status,p_guest_count:0,p_note:null});if(error)setError(error.message);else{setSuccess(status==="attending"?"Kehadiranmu sudah dikonfirmasi. Sampai jumpa di lokasi!":"Responsmu sudah tersimpan. Terima kasih sudah mengabari.");await load()}setSaving(false)};return <main className="invitation-page"><section className="invitation-card"><img src="/revolt-riders-logo.jpg" alt="Revolt Riders"/><em>UNDANGAN PERSONAL · {data?.member_external_id??"REVOLT RIDERS"}</em>{loading?<h1>Memuat undangan…</h1>:!data?<><h1>Undangan tidak ditemukan</h1><p>Token mungkin tidak valid atau agenda sudah tidak aktif.</p></>:<><h1>{data.event_title}</h1><p>{data.event_description??"Kehadiranmu adalah bagian penting dari perjalanan kita."}</p><div className="invitation-details"><span><CalendarDays/><b>{formatEventDate(data.start_at)}</b></span><span><MapPin/><b>{data.location_name??"Lokasi akan diumumkan"}</b></span></div>{data.location_url&&<a className="dark-action" href={data.location_url} target="_blank" rel="noreferrer">BUKA LOKASI</a>}<h2>Konfirmasi kehadiran</h2><div className="rsvp-actions"><button disabled={saving} className={data.rsvp_status==="attending"?"selected":""} onClick={()=>answer("attending")}><Check/>Hadir</button><button disabled={saving} className={data.rsvp_status==="declined"?"selected":""} onClick={()=>answer("declined")}><X/>Tidak hadir</button></div>{success&&<p className="success-message"><Check/>{success}</p>}</>}{error&&<p className="error-message">{error}</p>}<footer>REVOLT RIDERS · RR XXII · SITUBONDO</footer></section></main>}
