/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import {AppShell} from "@/components/app-shell";
import type {EventRecord} from "@/lib/domain";
import {formatEventDate,formatShortDate} from "@/lib/domain";
import {getSupabaseBrowserClient} from "@/lib/supabase/client";
import {CalendarDays,MapPin,RefreshCw} from "lucide-react";
import {useCallback,useEffect,useState} from "react";
export default function AgendaPage(){const[events,setEvents]=useState<EventRecord[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=useCallback(async()=>{try{const{data,error}=await getSupabaseBrowserClient().from("events").select("id,title,slug,type,description,location_name,location_url,start_at,end_at,meetup_at,status").in("status",["published","completed"]).order("start_at",{ascending:true});if(error)throw error;setEvents((data??[]) as EventRecord[])}catch(cause){setError(cause instanceof Error?cause.message:"Agenda gagal dimuat.")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);const refresh=()=>{setLoading(true);setError("");void load()};return <AppShell active="Agenda" title="Agenda"><div className="page-wrap"><section className="page-intro"><div><em>AGENDA KOMUNITAS</em><h2>Jadwal Revolt Riders</h2><p>Agenda resmi, lokasi kumpul, dan waktu keberangkatan dalam WIB.</p></div><button onClick={refresh} disabled={loading}><RefreshCw className={loading?"spin":""}/>Refresh</button></section>{error&&<p className="error-message">{error}</p>}<div className="event-grid">{events.map(event=>{const d=formatShortDate(event.start_at);return <article className="agenda-detail" id={event.slug} key={event.id}><time><b>{d.day}</b><small>{d.month}</small></time><div><em>{event.type}</em><h3>{event.title}</h3><p>{event.description??"Informasi lengkap akan diperbarui oleh pengurus."}</p><span><CalendarDays/>{formatEventDate(event.start_at)}</span><span><MapPin/>{event.location_name??"Lokasi menyusul"}</span>{event.location_url&&<a href={event.location_url} target="_blank" rel="noreferrer">Buka lokasi</a>}</div></article>})}</div>{!loading&&!error&&events.length===0&&<section className="empty-state card"><CalendarDays/><h2>Belum ada agenda</h2><p>Agenda yang dipublikasikan pengurus akan muncul otomatis di sini.</p></section>}</div></AppShell>}
