-- Historical migration version retained intentionally.
--
-- The original migration embedded the production Revolt Riders member dataset.
-- Real member records must be provisioned through the private operational import
-- flow and must never be committed to this public repository.
--
-- This migration is therefore intentionally a no-op so the migration version
-- remains present without shipping personal member data.